version: '3.3'
services:
  divein:
    image: sc-registry.fredhutch.org/divein:latest
    networks:
      - sc-swarm-net
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.divein.rule=Host(`divein.fredhutch.org`)"
        - "traefik.http.routers.divein-secured.rule=Host(`divein.fredhutch.org`)"
        - "traefik.http.routers.divein.entrypoints=web,web-secured"
        - "traefik.http.services.divein.loadbalancer.server.port=80" # it seems you always need to give traefik a port so it 'notices' the service
        - "traefik.http.routers.divein.tls=true"

networks:
  sc-swarm-net:
    external: true